package net.imagej.ops.segment.hough;

import net.imagej.ops.Op;

/**
 * Marker interface for Hough circle detector ops.
 * <p>
 * These ops retrieve the Hough circles from a vote image generated by a
 * {@link HoughCircleTransformOp}. The circles are returned as a collection of
 * {@link HoughCircle}s.
 * 
 * @author Jean-Yves Tinevez
 */
public interface HoughCircleDetectorOp extends Op
{

}
